name: Firebase Cleanup

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
          
      - name: Install
        run: bun install
        
      - name: Build with Vite
        run: bun run build --base=/cellpack-client
        
      - name: Run cleanup
        env:
          API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: bun run scripts/cleanup.ts