# Adapted from https://github.com/marketplace/actions/deploy-pr-preview.
name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Build with Vite
        run: bun run build --base=/cellpack-client/pr-preview/pr-${PR_NUMBER}/
        env:
          PR_NUMBER: ${{ github.event.number }}

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@430e3dfc1de8a8ae77e77d862d25676ef9db55d1
        with:
          source-dir: ./dist/
