name: run-tests
run-name: ✅ Checking '${{'#'}}${{github.ref_name}}' on branch '${{github.head_ref}}'
on: pull_request
jobs:
  static-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Run Linter
        run: bun run lint

      - name: Run Typechecker
        # Run type check even if the previous linter step failed
        if: success() || failure()
        run: bun run typeCheck

      - name: Run Tests
        # Run test even if the previous step(s) failed
        if: success() || failure()
        run: bun test --coverage

      - name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2.1.1